project:
  type: website

execute: 
  freeze: auto
language: 
  search-text-placeholder: Search

website: 
  favicon: images/Favicon.png
  google-analytics: 
    tracking-id: "G-54HL7T1Z2K"
  repo-url: https://github.com/noramcgregor/ds-essentials/
  repo-subdir: book
  repo-actions: [source, issue] 

    
  navbar:
    background: primary
    search: true
    type: overlay
    logo: Favicon.png
    
    left:
      - text: "Digital Scholarship & Data Science Essentials for Library Professionals"
        href: index.qmd

    right:
      - text: "Topic Guides"
        href: topicguides.qmd
      - text: "Additional Resources"
        menu:
        - references.qmd
        - dstp.qmd
        - reports.qmd 
        - training-platforms.qmd
        - networks.qmd
      - text: "Contribute"
        menu:
        - contributing.qmd
        - guidelines.qmd
        - licensing.qmd
      - text: "About"
        href: project-overview.qmd 
      - text: "Contact"
        href: contact.qmd    


  sidebar:  
      line-height: 2.5;
      - title: "Topic Guides"
        style: "floating"
        background: light
        contents:
          - topicguides.qmd
          - ai-ml.qmd
          - api.qmd
          - atr.qmd
          - collectionsasdata.qmd
          - computer-vision.qmd
          - copyright.qmd
          - crowdsourcing.qmd
          - dataviz.qmd
          - digitalmapping.qmd
          - github.qmd
          - iiif.qmd
          - lod.qmd
          - programming.qmd
          - openresearch.qmd
          - workingwdata.qmd 
  page-footer: 
    border: false
    background: "#EEB111"
    left: | 
      A 2023-2027 <a href="https://libereurope.eu/working-groups">LIBER Working Group</a> collaboration between <a href="https://libereurope.eu/working-group/digital-scholarship-and-digital-cultural-heritage-collections-working-group/">Digital Scholarship and Digital Cultural Heritage </a> and <a href="https://libereurope.eu/working-group/liber-data-science-in-libraries-working-group/">Data Science in Libraries</a> 
    right:
      - icon: github
        href: https://github.com/noramcgregor/ds-essentials

format:
  html:
    theme: [flatly, custom.scss]
    toc: true
    toc-location: right
    toc-title: Jump to...
    toc-depth: 2






#About DS Essentials - Topic Guides  -   Additional Resources  -  Contribute   -   Search

book:  
  title: "Digital Scholarship & Data Science Essentials for Library Professionals"
  google-analytics: 
    tracking-id: "G-54HL7T1Z2K"
  reader-mode: true
  search: true
  page-footer: 
    border: false
    background: dark
    left: | 
      A 2023-2027 <a href="https://libereurope.eu/working-groups">LIBER Working Group</a> collaboration between <a href="https://libereurope.eu/working-group/digital-scholarship-and-digital-cultural-heritage-collections-working-group/">Digital Scholarship and Digital Cultural Heritage </a> and <a href="https://libereurope.eu/working-group/liber-data-science-in-libraries-working-group/">Data Science in Libraries</a> 
  
  chapters:
    - part: "**ABOUT**"
      chapters:
        - index.qmd
        - project-overview.qmd
        - contributing.qmd
        - guidelines.qmd
        - licensing.qmd
        - contact.qmd
    - topicguides.qmd
    - ai-ml.qmd
    - copyright.qmd
    - atr.qmd
    - collectionsasdata.qmd
    - computer-vision.qmd
    - lod.qmd
    - iiif.qmd
    - dataviz.qmd
    - digitalmapping.qmd
    - crowdsourcing.qmd
    - github.qmd
    - workingwdata.qmd
    - part: "**GENERAL RESOURCES**"
      chapters:
        - dstp.qmd
        - references.qmd
        - reports.qmd
        - training-platforms.qmd
        - networks.qmd
        
    
  sidebar:
    logo: images/NewLogo.png
    style: "docked"
    collapse-level: 1

  comments: 
    utterances:
      repo: libereurope/ds-essentials

bibliography: references.bib




